FROM azukiapp/alpine:3.3
MAINTAINER Hugo Courtecuisse <hugo.courtecuisse@gmail.com>

# Create new folder
RUN mkdir /tmp/zdsback
WORKDIR /tmp/zdsback

# Add python dependency
RUN apk add --no-cache gcc python-dev py-pip py-virtualenv libffi-dev musl-dev libxml2-dev libxslt-dev libjpeg-turbo-dev zlib cairo

# Use virtualenv
RUN virtualenv zdsenv --python=python2
RUN source zdsenv/bin/activate 

# Download requirements.txt and requirements-dev.txt
RUN wget https://raw.githubusercontent.com/zestedesavoir/zds-site/dev/requirements.txt
RUN wget https://raw.githubusercontent.com/zestedesavoir/zds-site/dev/requirements-dev.txt

#ÂInstall back dependencies
RUN CFLAGS="$CFLAGS -L/lib" pip install --upgrade -r requirements.txt -r requirements-dev.txt 

# Create database
RUN printf "%s\n" "if [ ! -f /code/base.db ]; then" "cd /code" "echo \" Creation de la base de donnees \" " "python manage.py migrate" "python manage.py loaddata fixtures/*.yaml" "python manage.py load_factory_data fixtures/advanced/aide_tuto_media.yaml" "fi" "cd /code/" "echo \" Pour lancer le serveur, taper la commande python manage.py runserver 0.0.0.0:8000  \" " > /root/.bashrc && chmod +x /root/.bashrc

